"""
非遗剪纸知识图谱 — 内置种子数据
供开发和演示使用，涵盖常见纹样、母题、技法、流派、文化象征等
"""

from datetime import datetime

SEED_PAPER_CUT_PATTERNS = [
    {
        "id": "pc_001",
        "name": "龙凤呈祥",
        "full_name": "龙凤呈祥婚庆剪纸",
        "category": "传统纹样",
        "sub_category": ["婚庆", "祥瑞"],
        "description": "经典婚庆剪纸图案，龙凤环绕'囍'字，象征婚姻美满、夫妻和谐。龙居左凤居右，呈对称环绕之势。",
        "complexity": "复杂",
        "typical_dimensions": {"width": 40, "height": 40, "unit": "cm"},
        "recommended_colors": ["大红", "金色"],
        "color_count": 2,
        "meaning": "婚姻美满、龙凤和鸣、幸福吉祥",
        "cultural_context": "龙凤文化是中国传统文化的重要组成部分，龙代表阳刚、凤代表阴柔，龙凤呈祥寓意阴阳和谐、婚姻美满。",
        "era": "明清时期流行",
        "region": "全国广泛分布",
        "symmetry_type": "轴对称",
        "applicable_scenes": ["婚庆", "春节", "乔迁"],
        "difficulty_level": 4,
        "reference_image_url": "",
        "reference_source": "中国传统剪纸图鉴",
        "status": "已发布",
        "is_public": True,
        "popularity": 95,
        "tags": ["婚庆", "龙凤", "吉祥", "对称"],
        "created_by": "系统",
        "version": 1,
    },
    {
        "id": "pc_002",
        "name": "福寿双全",
        "full_name": "福寿双全祝寿剪纸",
        "category": "传统纹样",
        "sub_category": ["祝寿", "祈福"],
        "description": "蝙蝠（福）与寿桃（寿）组合图案，常用于祝寿场景。蝙蝠展翅环绕寿桃，间以祥云点缀。",
        "complexity": "中等",
        "typical_dimensions": {"width": 30, "height": 30, "unit": "cm"},
        "recommended_colors": ["大红", "深红"],
        "color_count": 1,
        "meaning": "福寿双全、健康长寿",
        "cultural_context": "蝙蝠谐音'福'，寿桃象征长寿，二者结合代表'福寿双全'，是民间剪纸最常见的吉祥主题之一。",
        "era": "清代以来",
        "region": "全国广泛分布",
        "symmetry_type": "中心对称",
        "applicable_scenes": ["祝寿", "春节", "敬老"],
        "difficulty_level": 3,
        "status": "已发布",
        "is_public": True,
        "popularity": 88,
        "tags": ["祝寿", "福", "寿桃", "蝙蝠"],
        "created_by": "系统",
        "version": 1,
    },
    {
        "id": "pc_003",
        "name": "喜上眉梢",
        "full_name": "喜上眉梢花鸟剪纸",
        "category": "传统纹样",
        "sub_category": ["花鸟", "吉祥"],
        "description": "喜鹊立于梅花枝头，'鹊'谐音'喜'，'梅'谐音'眉'，寓意喜事临门、心情愉悦。",
        "complexity": "中等",
        "recommended_colors": ["大红"],
        "color_count": 1,
        "meaning": "喜事临门、好运将至",
        "cultural_context": "以谐音表达吉祥寓意是民间剪纸的典型手法，喜鹊与梅花的组合在传统剪纸中极为常见。",
        "era": "明清时期",
        "region": "北方地区",
        "symmetry_type": "不对称",
        "applicable_scenes": ["春节", "喜庆", "装饰"],
        "difficulty_level": 3,
        "status": "已发布",
        "is_public": True,
        "popularity": 82,
        "tags": ["喜鹊", "梅花", "谐音吉祥"],
        "created_by": "系统",
        "version": 1,
    },
    {
        "id": "pc_004",
        "name": "年年有余",
        "full_name": "年年有余连年有余剪纸",
        "category": "传统纹样",
        "sub_category": ["年俗", "吉祥"],
        "description": "莲花与鲤鱼组合图案，'莲'谐音'连'，'鱼'谐音'余'，寓意年年有余、生活富足。常伴以水波纹。",
        "complexity": "中等",
        "recommended_colors": ["大红", "粉红", "绿色"],
        "color_count": 3,
        "meaning": "年年有余、丰衣足食、富贵吉祥",
        "cultural_context": "鱼和莲花的组合是农耕文化中对丰收富足生活向往的典型表达，在北方年俗剪纸中尤盛。",
        "era": "宋代以来",
        "region": "全国广泛分布",
        "symmetry_type": "中心对称",
        "applicable_scenes": ["春节", "年俗", "祈福"],
        "difficulty_level": 3,
        "status": "已发布",
        "is_public": True,
        "popularity": 90,
        "tags": ["鲤鱼", "莲花", "谐音", "年俗"],
        "created_by": "系统",
        "version": 1,
    },
    {
        "id": "pc_005",
        "name": "十二生肖·龙",
        "full_name": "生肖龙剪纸",
        "category": "传统纹样",
        "sub_category": ["生肖", "动物"],
        "description": "腾龙剪纸，龙首高昂，五爪张开，身绕祥云。用于龙年生肖装饰和祈福。",
        "complexity": "复杂",
        "recommended_colors": ["金色", "大红"],
        "color_count": 2,
        "meaning": "龙腾盛世、吉祥权威",
        "cultural_context": "龙是中华民族的图腾，十二生肖中唯一的神话动物，龙年剪纸具有特殊的文化意义。",
        "era": "历代传承",
        "region": "全国广泛分布",
        "symmetry_type": "轴对称",
        "applicable_scenes": ["生肖年", "春节", "祈福"],
        "difficulty_level": 5,
        "status": "已发布",
        "is_public": True,
        "popularity": 92,
        "tags": ["生肖", "龙", "图腾", "祥云"],
        "created_by": "系统",
        "version": 1,
    },
    {
        "id": "pc_006",
        "name": "四君子·梅兰竹菊",
        "full_name": "四君子系列剪纸",
        "category": "传统纹样",
        "sub_category": ["花卉", "文人", "品格"],
        "description": "梅兰竹菊四君子以窗格形式组合，寓意君子品格高洁。梅傲雪、兰幽香、竹虚心、菊凌霜。",
        "complexity": "极复杂",
        "recommended_colors": ["大红", "黑色", "白色"],
        "color_count": 1,
        "meaning": "君子品格、气节高尚",
        "cultural_context": "梅兰竹菊代表中国传统文人推崇的四类高尚品格，是文人剪纸和书画剪纸的重要题材。",
        "era": "唐宋以来",
        "region": "全国广泛分布",
        "symmetry_type": "轴对称",
        "applicable_scenes": ["装饰", "文人", "春节"],
        "difficulty_level": 5,
        "status": "已发布",
        "is_public": True,
        "popularity": 85,
        "tags": ["梅花", "兰花", "竹子", "菊花", "四君子"],
        "created_by": "系统",
        "version": 1,
    },
    {
        "id": "pc_007",
        "name": "五福捧寿",
        "full_name": "五福捧寿团花剪纸",
        "category": "传统纹样",
        "sub_category": ["祝寿", "团花"],
        "description": "圆形团花构图，五只蝙蝠围绕中央寿字或寿桃，外圈配以万字不到头纹。",
        "complexity": "复杂",
        "typical_dimensions": {"width": 35, "height": 35, "unit": "cm"},
        "recommended_colors": ["大红", "金色"],
        "color_count": 2,
        "meaning": "五福俱全、长寿安康——五福指长寿、富贵、康宁、好德、善终",
        "cultural_context": "'五福捧寿'源于《尚书·洪范》，是传统祝寿剪纸中最尊贵的图案之一，常用于长辈寿辰。",
        "era": "明代以来",
        "region": "全国普遍",
        "symmetry_type": "中心对称",
        "applicable_scenes": ["祝寿", "春节", "祈福"],
        "difficulty_level": 4,
        "status": "已发布",
        "is_public": True,
        "popularity": 87,
        "tags": ["五蝠", "寿字", "团花", "祝寿"],
        "created_by": "系统",
        "version": 1,
    },
    {
        "id": "pc_008",
        "name": "狮子滚绣球",
        "full_name": "狮子滚绣球镇宅剪纸",
        "category": "民俗纹样",
        "sub_category": ["瑞兽", "镇宅"],
        "description": "雄狮脚踏绣球，姿态威猛，绣球上的绶带飘逸灵动。用于镇宅辟邪、祈求平安。",
        "complexity": "复杂",
        "recommended_colors": ["大红", "黑色"],
        "color_count": 2,
        "meaning": "镇宅辟邪、吉祥平安",
        "cultural_context": "狮子是瑞兽，绣球象征圆满吉祥。'狮子滚绣球'是北方民俗剪纸的代表题材，常见于门笺和窗花。",
        "era": "明清时期",
        "region": "北方地区",
        "symmetry_type": "不对称",
        "applicable_scenes": ["镇宅", "春节", "庙会"],
        "difficulty_level": 4,
        "status": "已发布",
        "is_public": True,
        "popularity": 78,
        "tags": ["狮子", "绣球", "瑞兽", "镇宅"],
        "created_by": "系统",
        "version": 1,
    },
    {
        "id": "pc_009",
        "name": "花开富贵",
        "full_name": "花开富贵牡丹剪纸",
        "category": "传统纹样",
        "sub_category": ["花卉", "富贵"],
        "description": "盛开的牡丹花配以蝴蝶和枝叶，花瓣层次丰富，富丽堂皇。",
        "complexity": "中等",
        "recommended_colors": ["大红", "粉红", "绿色"],
        "color_count": 3,
        "meaning": "富贵吉祥、繁荣昌盛",
        "cultural_context": "牡丹被称为'花中之王'，象征富贵。牡丹蝴蝶的组合是民间剪纸中最受欢迎的花卉题材之一。",
        "era": "唐代以来",
        "region": "全国广泛分布",
        "symmetry_type": "中心对称",
        "applicable_scenes": ["装饰", "春节", "乔迁"],
        "difficulty_level": 3,
        "status": "已发布",
        "is_public": True,
        "popularity": 91,
        "tags": ["牡丹", "蝴蝶", "富贵", "花卉"],
        "created_by": "系统",
        "version": 1,
    },
    {
        "id": "pc_010",
        "name": "麒麟送子",
        "full_name": "麒麟送子祈福剪纸",
        "category": "民俗纹样",
        "sub_category": ["祈福", "求子"],
        "description": "麒麟背驮童子，手持莲花或如意，周围祥云缭绕。寓意子孙昌盛、家族兴旺。",
        "complexity": "复杂",
        "recommended_colors": ["大红", "金色"],
        "color_count": 2,
        "meaning": "早生贵子、子孙昌盛",
        "cultural_context": "麒麟为仁瑞之兽，'麒麟送子'源于古代求子习俗，在北方婚俗剪纸中占有重要地位。",
        "era": "清代以来",
        "region": "北方地区",
        "symmetry_type": "不对称",
        "applicable_scenes": ["婚庆", "求子", "祈福"],
        "difficulty_level": 4,
        "status": "已发布",
        "is_public": True,
        "popularity": 80,
        "tags": ["麒麟", "送子", "童子", "祈福"],
        "created_by": "系统",
        "version": 1,
    },
    {
        "id": "pc_011",
        "name": "连理枝",
        "full_name": "连理枝并蒂莲剪纸",
        "category": "传统纹样",
        "sub_category": ["婚庆", "花卉"],
        "description": "两株莲花同根并蒂，枝叶交错相连，寓意夫妻恩爱、永不分离。",
        "complexity": "中等",
        "recommended_colors": ["大红", "粉红"],
        "color_count": 2,
        "meaning": "夫妻恩爱、姻缘美满、永结同心",
        "cultural_context": "'在天愿作比翼鸟，在地愿为连理枝'——唐代白居易诗句，连理枝成为忠贞爱情的象征。",
        "era": "唐代以来",
        "region": "南方地区",
        "symmetry_type": "轴对称",
        "applicable_scenes": ["婚庆", "情人节", "纪念"],
        "difficulty_level": 3,
        "status": "已发布",
        "is_public": True,
        "popularity": 75,
        "tags": ["并蒂莲", "爱情", "婚庆"],
        "created_by": "系统",
        "version": 1,
    },
    {
        "id": "pc_012",
        "name": "鱼戏莲",
        "full_name": "鱼戏莲叶间剪纸",
        "category": "传统纹样",
        "sub_category": ["动物", "水生", "吉祥"],
        "description": "锦鲤穿梭于莲叶莲花之间，水波流动，画面生动活泼。",
        "complexity": "中等",
        "recommended_colors": ["大红", "绿色", "蓝色"],
        "color_count": 3,
        "meaning": "自由自在、连年有余、阴阳和谐",
        "cultural_context": "鱼戏莲在民俗文化中既代表'连年有余'的谐音吉祥，又暗含阴阳相合的生殖崇拜寓意。",
        "era": "宋代以来",
        "region": "南方地区",
        "symmetry_type": "不对称",
        "applicable_scenes": ["装饰", "春节", "婚庆"],
        "difficulty_level": 3,
        "status": "已发布",
        "is_public": True,
        "popularity": 83,
        "tags": ["鲤鱼", "莲花", "水", "动态"],
        "created_by": "系统",
        "version": 1,
    },
    {
        "id": "pc_101",
        "name": "戏剧人物·贵妃醉酒",
        "full_name": "京剧人物剪纸——贵妃醉酒",
        "category": "创新纹样",
        "sub_category": ["人物", "戏曲"],
        "description": "杨贵妃醉酒后的婀娜姿态，头戴凤冠，身着戏袍，水袖轻扬。融合京剧舞台造型。",
        "complexity": "极复杂",
        "recommended_colors": ["黑色", "金色", "红色"],
        "color_count": 3,
        "meaning": "艺术之美、传统文化传承",
        "cultural_context": "戏曲人物剪纸是中国剪纸的重要分支，以京剧人物为题材的剪纸在北方流派中尤为突出。",
        "era": "近现代",
        "region": "北方地区",
        "symmetry_type": "不对称",
        "applicable_scenes": ["装饰", "文化展示", "收藏"],
        "difficulty_level": 5,
        "status": "已发布",
        "is_public": True,
        "popularity": 75,
        "tags": ["戏曲", "人物", "京剧", "杨贵妃"],
        "created_by": "系统",
        "version": 1,
    },
    {
        "id": "pc_102",
        "name": "剪纸·清明上河图(局部)",
        "full_name": "清明上河图剪纸长卷",
        "category": "创新纹样",
        "sub_category": ["长卷", "名画改编"],
        "description": "以北宋张择端《清明上河图》为蓝本创作的剪纸长卷局部，展现汴河两岸市井繁华。",
        "complexity": "极复杂",
        "typical_dimensions": {"width": 100, "height": 30, "unit": "cm"},
        "recommended_colors": ["白色", "黑色", "金色"],
        "color_count": 1,
        "meaning": "文化传承、艺术再现",
        "cultural_context": "以经典绘画为蓝本进行剪纸再创作，是中国现代剪纸艺术创新的重要方向。",
        "era": "当代",
        "region": "全国",
        "symmetry_type": "不对称",
        "applicable_scenes": ["展览", "收藏", "文化礼品"],
        "difficulty_level": 5,
        "status": "已发布",
        "is_public": True,
        "popularity": 72,
        "tags": ["清明上河图", "长卷", "市井", "宋代"],
        "created_by": "系统",
        "version": 1,
    },
]

# ========== 纹样母题数据 ==========

SEED_MOTIFS = [
    {
        "id": "motif_001",
        "name": "龙纹",
        "category": "动物",
        "sub_category": "神话动物",
        "description": "中国传统龙形纹样，有腾龙、团龙、行龙、升龙等多种形态。",
        "symbolic_meaning": "权威、吉祥、阳刚、中华民族图腾",
        "cultural_background": "龙是中华民族最核心的文化图腾，源于远古部落崇拜，历经数千年演变。",
        "typical_techniques": ["阴刻", "阳刻", "阴阳刻"],
        "common_regions": ["全国", "北方地区"],
        "style_variants": ["腾龙", "团龙", "行龙", "升龙", "降龙"],
    },
    {
        "id": "motif_002",
        "name": "凤纹",
        "category": "动物",
        "sub_category": "神话动物",
        "description": "凤凰纹样，有丹凤朝阳、凤穿牡丹、龙凤呈祥等经典构图。",
        "symbolic_meaning": "高贵、美丽、祥瑞、阴柔之美",
        "cultural_background": "凤凰是百鸟之王，与龙并列为中国传统两大图腾，代表和平与繁荣。",
        "typical_techniques": ["阳刻", "阴阳刻"],
        "common_regions": ["全国"],
        "style_variants": ["丹凤", "凤穿牡丹", "团凤"],
    },
    {
        "id": "motif_003",
        "name": "云纹",
        "category": "自然景观",
        "sub_category": "天象",
        "description": "中国传统云形纹样，有如意云、流云、层云等多种变化。",
        "symbolic_meaning": "吉祥、高升、如意",
        "cultural_background": "云在中国文化中代表天象祥瑞，云纹是剪纸中最常用的辅助纹样之一。",
        "typical_techniques": ["阴刻", "阳刻"],
        "common_regions": ["全国"],
        "style_variants": ["如意云", "流云", "层云", "卷云"],
    },
    {
        "id": "motif_004",
        "name": "牡丹",
        "category": "植物",
        "sub_category": "花卉",
        "description": "牡丹花形纹样，花瓣层次丰富，有单瓣、重瓣、千层等多种表现。",
        "symbolic_meaning": "富贵、华丽、繁荣昌盛",
        "cultural_background": "牡丹为'花中之王'，自唐代起即为富贵吉祥的象征。",
        "typical_techniques": ["阴刻", "阳刻"],
        "common_regions": ["全国"],
        "style_variants": ["盛开牡丹", "含苞牡丹", "牡丹团花"],
    },
    {
        "id": "motif_005",
        "name": "蝙蝠纹",
        "category": "动物",
        "sub_category": "瑞兽",
        "description": "蝙蝠展翅纹样，因'蝠'谐音'福'成为最重要的吉祥符号之一。",
        "symbolic_meaning": "福气、幸运、福运",
        "cultural_background": "蝙蝠在西方文化中常象征黑暗，但在中国传统文化中因谐音成为最受欢迎的吉祥符号。",
        "typical_techniques": ["阴刻"],
        "common_regions": ["全国"],
        "style_variants": ["单蝠", "双蝠", "五蝠"],
    },
    {
        "id": "motif_006",
        "name": "寿桃",
        "category": "植物",
        "sub_category": "果实",
        "description": "寿桃纹样，从枝叶到果实，寄托健康长寿的祝愿。",
        "symbolic_meaning": "长寿、健康、永恒",
        "cultural_background": "源自西王母蟠桃盛会的传说，寿桃是传统祝寿剪纸的核心母题。",
        "typical_techniques": ["阳刻", "阴阳刻"],
        "common_regions": ["全国"],
        "style_variants": ["单桃", "双桃", "九桃"],
    },
    {
        "id": "motif_007",
        "name": "万字纹",
        "category": "几何",
        "sub_category": "连续纹样",
        "description": "卍字连续纹样，可向四方无限延伸。",
        "symbolic_meaning": "吉祥万德、永恒光明",
        "cultural_background": "源自佛教卍字符号，在民间被广泛用作底纹和边框装饰。",
        "typical_techniques": ["阴刻"],
        "common_regions": ["全国"],
        "style_variants": ["万字不到头", "万字锦"],
    },
    {
        "id": "motif_008",
        "name": "荷花/莲花",
        "category": "植物",
        "sub_category": "花卉",
        "description": "出水芙蓉纹样，有莲花、莲叶、莲蓬、莲藕等多种表现。",
        "symbolic_meaning": "纯洁、高雅、出淤泥而不染",
        "cultural_background": "莲花在佛教中代表净土，在儒家代表君子品格，在民间代表多子多福。",
        "typical_techniques": ["阳刻", "阴阳刻"],
        "common_regions": ["南方地区"],
        "style_variants": ["并蒂莲", "莲鲤图", "出水芙蓉"],
    },
    {
        "id": "motif_009",
        "name": "喜鹊",
        "category": "动物",
        "sub_category": "鸟类",
        "description": "喜鹊纹样，常与梅花搭配，是报喜鸟的象征。",
        "symbolic_meaning": "喜事、好运、报喜",
        "cultural_background": "喜鹊被称为'报喜鸟'，与梅花组合为'喜上眉(梅)梢'，是民间最受欢迎的吉祥组合之一。",
        "typical_techniques": ["阳刻"],
        "common_regions": ["北方地区"],
        "style_variants": ["单鹊", "双鹊", "鹊梅图"],
    },
    {
        "id": "motif_010",
        "name": "锦鲤/鱼纹",
        "category": "动物",
        "sub_category": "水生",
        "description": "鱼形纹样，有鲤鱼、金鱼、鲶鱼等多种，常与莲花、水波搭配。",
        "symbolic_meaning": "富裕、年年有余、金玉满堂",
        "cultural_background": "'鱼'谐音'余'，代表富足有余。鲤鱼跳龙门更代表功成名就。",
        "typical_techniques": ["阴刻", "阳刻"],
        "common_regions": ["全国"],
        "style_variants": ["鲤鱼", "金鱼", "双鱼", "九鱼图"],
    },
    {
        "id": "motif_011",
        "name": "梅花",
        "category": "植物",
        "sub_category": "花卉",
        "description": "梅花纹样，五瓣为典型，有疏影横斜、繁花似锦等风格。",
        "symbolic_meaning": "坚韧、高洁、傲骨、报春",
        "cultural_background": "梅花于寒冬绽放，象征坚韧不屈的品格。五瓣梅花也代表五福。",
        "typical_techniques": ["阳刻"],
        "common_regions": ["全国"],
        "style_variants": ["五瓣梅", "喜鹊登梅", "梅花篆字"],
    },
    {
        "id": "motif_012",
        "name": "福字纹",
        "category": "几何",
        "sub_category": "文字",
        "description": "以福字为核心进行艺术化变形的纹样，有圆福、长福、百福等多种。",
        "symbolic_meaning": "福气、好运、幸福",
        "cultural_background": "福字是春节剪纸中最常见的文字纹样，倒贴福字寓意'福到了'。",
        "typical_techniques": ["阴刻", "阳刻"],
        "common_regions": ["全国"],
        "style_variants": ["正福", "圆福", "百福图"],
    },
]

# ========== 技法数据 ==========

SEED_TECHNIQUES = [
    {
        "id": "tech_001",
        "name": "阴刻",
        "category": "阴刻",
        "description": "刻去图案的线条，保留背景，形成以白线（负形）表现图案的效果。",
        "difficulty_level": 3,
        "tools_required": ["刻刀", "刻板", "蜡盘"],
        "skill_points": ["运刀力度均匀", "线条流畅连贯", "转折处圆润自然"],
        "typical_effects": "白色线条在红纸上呈现的对比效果，线条细腻精致",
        "origin_region": "全国",
        "is_traditional": True,
        "history": "阴刻是最古老的剪纸技法之一，与雕刻中的阴刻手法一脉相承。",
    },
    {
        "id": "tech_002",
        "name": "阳刻",
        "category": "阳刻",
        "description": "保留图案的线条，刻去背景，形成以红纸（正形）表现图案的效果。",
        "difficulty_level": 4,
        "tools_required": ["刻刀", "刻板", "蜡盘", "镊子"],
        "skill_points": ["图案轮廓精准", "大面积镂空时保持纸面完整", "精细处不断线"],
        "typical_effects": "红色实体图案浮于白色底上，轮廓清晰有力",
        "origin_region": "全国",
        "is_traditional": True,
        "history": "阳刻是剪纸中最常见的表现手法，与印章中的阳刻技法相通。",
    },
    {
        "id": "tech_003",
        "name": "阴阳刻结合",
        "category": "阴阳刻",
        "description": "在同一作品中同时运用阴刻和阳刻，形成虚实相生的丰富效果。",
        "difficulty_level": 5,
        "tools_required": ["刻刀", "刻板", "蜡盘", "镊子"],
        "skill_points": ["阴线阳面布局合理", "过渡自然不突兀", "整体协调统一"],
        "typical_effects": "层次丰富，虚实对比强烈，画面立体感强",
        "origin_region": "全国",
        "is_traditional": True,
        "history": "阴阳刻结合是成熟期剪纸技法的标志，在蔚县剪纸中达到艺术高峰。",
    },
    {
        "id": "tech_004",
        "name": "套色剪纸",
        "category": "套色剪纸",
        "description": "在不同颜色的纸上分别刻出图案的不同部分，然后拼贴组合，形成彩色剪纸。",
        "difficulty_level": 5,
        "tools_required": ["各色彩纸", "刻刀", "刻板", "浆糊", "镊子"],
        "skill_points": ["色彩搭配和谐", "不同色层对齐精准", "拼贴无痕"],
        "typical_effects": "色彩丰富绚丽，具有装饰画效果",
        "origin_region": "河北蔚县",
        "is_traditional": True,
        "history": "套色剪纸是蔚县剪纸的代表性技法，以'三分刻七分染'著称。",
    },
    {
        "id": "tech_005",
        "name": "单色剪纸",
        "category": "阴刻",
        "description": "使用单色纸（通常为红色）完成的剪纸，是剪纸最基本的技法形式。",
        "difficulty_level": 2,
        "tools_required": ["剪刀或刻刀", "红纸"],
        "skill_points": ["造型简洁有力", "构图饱满", "线条疏密有致"],
        "typical_effects": "纯粹热烈，民间气息浓郁",
        "origin_region": "全国",
        "is_traditional": True,
        "history": "单色剪纸是剪纸艺术最原始的形式，以红色为主流。",
    },
    {
        "id": "tech_006",
        "name": "剪刻结合",
        "category": "阴刻",
        "description": "大幅轮廓用剪刀剪出，精细部位用刻刀刻制，兼顾效率与精细度。",
        "difficulty_level": 3,
        "tools_required": ["剪刀", "刻刀", "刻板"],
        "skill_points": ["剪刻转换自然", "剪刀走弧线流畅", "刻刀走直线精准"],
        "typical_effects": "大幅面作品既有气势又有细节",
        "origin_region": "全国",
        "is_traditional": True,
    },
    {
        "id": "tech_007",
        "name": "染色剪纸",
        "category": "染纸",
        "description": "在白色宣纸上刻出图案后，用毛笔蘸取各色染料进行点染着色。",
        "difficulty_level": 4,
        "tools_required": ["宣纸", "刻刀", "毛笔", "染料（品色）", "蜡盘"],
        "skill_points": ["染料渗透均匀", "色彩过渡自然", "水分控制精准"],
        "typical_effects": "色彩明快，水色淋漓，类似年画效果",
        "origin_region": "河北蔚县",
        "is_traditional": True,
        "history": "染色剪纸是蔚县剪纸的王牌技艺，王老赏等大师将这一技法推向极致。",
    },
]

# ========== 地域流派数据 ==========

SEED_REGIONAL_STYLES = [
    {
        "id": "style_001",
        "name": "蔚县剪纸",
        "region": "蔚县",
        "province": "河北省",
        "history": "蔚县剪纸源于明代，兴盛于清代，以'阴刻为主、阳刻为辅、彩色点染'为特色，是中国最具代表性的剪纸流派之一。",
        "characteristics": "构图饱满、造型生动、色彩绚丽、技法细腻。以戏曲人物、花鸟鱼虫为主要题材。采用刻刀雕刻而非剪刀剪制。",
        "typical_motifs": ["戏剧人物", "花鸟", "脸谱"],
        "representative_works": ["《清明上河图》剪纸长卷", "《百蝶图》"],
        "representative_inheritors": ["王老赏", "任玉德", "周淑英"],
        "style_tags": ["细腻", "色彩丰富", "刻纸为主", "戏曲题材"],
        "influence_scope": "全国乃至国际",
        "status": "活跃",
        "protection_level": "国家级非遗",
    },
    {
        "id": "style_002",
        "name": "扬州剪纸",
        "region": "扬州",
        "province": "江苏省",
        "history": "扬州剪纸源于唐代，盛于明清。以线条流畅、造型雅致著称，与扬州园林文化一脉相承。",
        "characteristics": "线条流畅细腻、构图空灵透气、格调清新雅致。以花卉、山水、书法为主要题材。注重留白。",
        "typical_motifs": ["菊花", "梅花", "书法", "山水"],
        "representative_works": ["《梅兰竹菊》四条屏", "《扬州风景》"],
        "representative_inheritors": ["张永寿", "张慕莉"],
        "style_tags": ["细腻", "雅致", "文人气息", "留白"],
        "influence_scope": "华东地区",
        "status": "活跃",
        "protection_level": "国家级非遗",
    },
    {
        "id": "style_003",
        "name": "陕北剪纸",
        "region": "陕北",
        "province": "陕西省",
        "history": "陕北剪纸源于汉代，是中国最古老的剪纸流派之一。保留了大量原始图腾和民间信仰元素。",
        "characteristics": "粗犷豪放、造型古朴、夸张变形、寓意深厚。以民俗生活、神话传说、生肖动物为主要题材。",
        "typical_motifs": ["抓髻娃娃", "蛇盘兔", "狮子", "十二生肖"],
        "representative_works": ["《抓髻娃娃》", "《蛇盘兔》"],
        "representative_inheritors": ["库淑兰", "高凤莲", "刘洁琼"],
        "style_tags": ["粗犷", "古朴", "民俗", "图腾"],
        "influence_scope": "西北地区",
        "status": "活跃",
        "protection_level": "国家级非遗",
    },
    {
        "id": "style_004",
        "name": "佛山剪纸",
        "region": "佛山",
        "province": "广东省",
        "history": "佛山剪纸源于宋代，盛于明清。受岭南文化和海外贸易影响，形成了独特的风格。",
        "characteristics": "构图严谨、色彩浓艳、金碧辉煌。大量使用金纸和衬色技法。题材兼有传统和岭南地方特色。",
        "typical_motifs": ["狮子", "龙船", "荔枝", "粤剧人物"],
        "representative_works": ["《赛龙舟》", "《舞狮》"],
        "representative_inheritors": ["陈永才", "何燕"],
        "style_tags": ["金碧", "浓艳", "岭南特色"],
        "influence_scope": "华南地区及东南亚",
        "status": "活跃",
        "protection_level": "国家级非遗",
    },
    {
        "id": "style_005",
        "name": "漳浦剪纸",
        "region": "漳浦",
        "province": "福建省",
        "history": "漳浦剪纸源于唐代，以女性传承为主，是中国南方剪纸的重要代表。",
        "characteristics": "纤巧秀丽、细腻入微、写实与装饰并重。以民俗题材和闽南生活场景见长。",
        "typical_motifs": ["闽南民俗", "花鸟", "人物"],
        "representative_works": ["《水仙花》", "《闽南婚俗》"],
        "representative_inheritors": ["陈秋日", "高少苹"],
        "style_tags": ["纤巧", "秀丽", "女性传承"],
        "influence_scope": "闽南地区",
        "status": "活跃",
        "protection_level": "国家级非遗",
    },
    {
        "id": "style_006",
        "name": "高密剪纸",
        "region": "高密",
        "province": "山东省",
        "history": "高密剪纸源于明代，与高密扑灰年画、泥塑并称'高密三绝'。",
        "characteristics": "造型拙朴、意趣天成、金石味浓。善用锯齿纹、月牙纹等基本纹样组合。线条粗中带细。",
        "typical_motifs": ["水浒人物", "民间传说", "花鸟"],
        "representative_works": ["《水浒一百单八将》", "《老鼠娶亲》"],
        "representative_inheritors": ["范祚信", "齐秀花"],
        "style_tags": ["拙朴", "金石味", "水浒题材"],
        "influence_scope": "山东省",
        "status": "活跃",
        "protection_level": "国家级非遗",
    },
]

# ========== 文化象征数据 ==========

SEED_CULTURAL_SYMBOLS = [
    {
        "id": "symbol_001",
        "name": "福",
        "category": "吉祥",
        "meaning": "幸福、福气、好运。五福：长寿、富贵、康宁、好德、善终。",
        "typical_scenes": ["春节", "婚庆", "乔迁", "寿辰"],
        "related_holidays": ["春节", "元宵节"],
        "related_motifs": ["蝙蝠纹", "福字纹"],
        "cultural_origin": "源于古代祭祀祈福仪式，《尚书·洪范》最早提出五福概念。",
        "positive_keywords": ["福气", "好运", "幸福", "吉祥"],
    },
    {
        "id": "symbol_002",
        "name": "寿",
        "category": "吉祥",
        "meaning": "长寿、健康、生命绵长",
        "typical_scenes": ["祝寿", "春节", "敬老活动"],
        "related_holidays": ["春节", "重阳节"],
        "related_motifs": ["寿桃", "蝙蝠纹", "鹤"],
        "cultural_origin": "中国传统孝道文化的重要组成部分，长寿是五福之首。",
        "positive_keywords": ["长寿", "安康", "延年", "益寿"],
    },
    {
        "id": "symbol_003",
        "name": "喜",
        "category": "喜庆",
        "meaning": "喜庆、欢乐、好事来临",
        "typical_scenes": ["婚庆", "春节", "生子", "升迁"],
        "related_holidays": ["春节", "元宵节"],
        "related_motifs": ["喜鹊", "双喜", "梅花"],
        "cultural_origin": "喜文化是中国民俗文化的重要组成，'双喜临门'是最高级别的喜庆表达。",
        "positive_keywords": ["喜庆", "欢乐", "好事", "如意"],
    },
    {
        "id": "symbol_004",
        "name": "财",
        "category": "吉祥",
        "meaning": "财富、富贵、财运亨通",
        "typical_scenes": ["春节", "开业", "乔迁"],
        "related_holidays": ["春节", "财神诞"],
        "related_motifs": ["金元宝", "铜钱", "聚宝盆"],
        "cultural_origin": "源于民间财神信仰，是中国民间剪纸最受欢迎的题材之一。",
        "positive_keywords": ["发财", "富贵", "财源", "财运"],
    },
    {
        "id": "symbol_005",
        "name": "吉祥如意",
        "category": "吉祥",
        "meaning": "万事顺利、心想事成、好运相伴",
        "typical_scenes": ["春节", "婚庆", "送礼"],
        "related_holidays": ["春节"],
        "related_motifs": ["如意", "祥云", "灵芝"],
        "cultural_origin": "如意原为佛教法器，后演变为吉祥物，象征心想事成。",
        "positive_keywords": ["如意", "顺利", "好运", "吉祥"],
    },
    {
        "id": "symbol_006",
        "name": "辟邪",
        "category": "避邪",
        "meaning": "驱除邪祟、保佑平安、镇宅护佑",
        "typical_scenes": ["春节", "端午", "新居"],
        "related_holidays": ["春节", "端午节"],
        "related_motifs": ["狮子", "钟馗", "五毒", "虎"],
        "cultural_origin": "源于原始宗教的驱邪仪式，民间剪纸中的五毒、狮子等均为辟邪题材。",
        "positive_keywords": ["辟邪", "镇宅", "平安", "驱邪"],
    },
    {
        "id": "symbol_007",
        "name": "婚姻美满",
        "category": "喜庆",
        "meaning": "夫妻恩爱、白头偕老、家庭和睦",
        "typical_scenes": ["婚庆", "纪念日"],
        "related_holidays": ["七夕"],
        "related_motifs": ["龙凤", "并蒂莲", "鸳鸯", "双喜"],
        "cultural_origin": "中国传统婚俗文化核心观念。龙凤呈祥、并蒂莲等均为婚庆吉祥符号。",
        "positive_keywords": ["恩爱", "白头", "同心", "美满"],
    },
    {
        "id": "symbol_008",
        "name": "富贵",
        "category": "吉祥",
        "meaning": "财富与地位、生活富足美好",
        "typical_scenes": ["春节", "乔迁", "开业"],
        "related_holidays": ["春节"],
        "related_motifs": ["牡丹", "金鱼", "聚宝盆"],
        "cultural_origin": "富贵是中国人最普遍的愿望之一，牡丹象征富贵，'花开富贵'是经典剪纸题材。",
        "positive_keywords": ["富贵", "华丽", "丰裕", "繁荣"],
    },
]

# ========== 传承人数据 ==========

SEED_INHERITORS = [
    {
        "id": "inheritor_001",
        "name": "王老赏",
        "title": "已故剪纸大师",
        "gender": "男",
        "birth_year": 1893,
        "region": "河北省蔚县",
        "style_affiliation": ["蔚县剪纸"],
        "biography": "王老赏（1893-1968），河北蔚县人，蔚县剪纸艺术大师。以戏曲人物剪纸闻名，一生创作数千幅作品，被誉为'剪纸王'。",
        "specialties": ["戏曲人物剪纸", "阴刻技法"],
        "master_level": "大师级",
        "years_of_experience": 60,
        "representative_works": ["《三国演义》戏曲人物系列", "《百蝶图》"],
        "status": "已故",
        "is_reviewer": False,
    },
    {
        "id": "inheritor_002",
        "name": "库淑兰",
        "title": "中国民间剪纸艺术大师",
        "gender": "女",
        "birth_year": 1920,
        "region": "陕西省旬邑县",
        "style_affiliation": ["陕北剪纸"],
        "biography": "库淑兰（1920-2004），陕西旬邑人，被联合国教科文组织授予'中国民间工艺美术大师'称号。以彩色剪纸拼贴独具一格。",
        "specialties": ["彩色拼贴剪纸", "民俗题材"],
        "master_level": "大师级",
        "years_of_experience": 70,
        "representative_works": ["《剪花娘子》系列"],
        "awards": ["联合国教科文组织民间工艺美术大师"],
        "status": "已故",
        "is_reviewer": False,
    },
    {
        "id": "inheritor_003",
        "name": "周淑英",
        "title": "国家级非遗传承人",
        "gender": "女",
        "birth_year": 1964,
        "region": "河北省蔚县",
        "style_affiliation": ["蔚县剪纸"],
        "biography": "周淑英，河北蔚县人，国家级非物质文化遗产代表性传承人。师从父亲周永明，擅长染色剪纸。",
        "specialties": ["染色剪纸", "套色剪纸", "花鸟题材"],
        "master_level": "大师级",
        "years_of_experience": 40,
        "representative_works": ["《清明上河图》剪纸", "《百鸟朝凤》"],
        "awards": ["国家级非遗传承人", "中国民间文艺山花奖"],
        "status": "活跃",
        "is_reviewer": True,
    },
    {
        "id": "inheritor_004",
        "name": "张永寿",
        "title": "中国剪纸大师",
        "gender": "男",
        "birth_year": 1907,
        "region": "江苏省扬州市",
        "style_affiliation": ["扬州剪纸"],
        "biography": "张永寿（1907-1989），江苏扬州人，扬州剪纸艺术大师。以菊花剪纸著称，独创'叠剪法'。",
        "specialties": ["菊花剪纸", "叠剪法"],
        "master_level": "大师级",
        "years_of_experience": 70,
        "representative_works": ["《百菊图》", "《梅兰竹菊》四条屏"],
        "status": "已故",
        "is_reviewer": False,
    },
    {
        "id": "inheritor_005",
        "name": "陈永才",
        "title": "国家级非遗传承人",
        "gender": "男",
        "birth_year": 1941,
        "region": "广东省佛山市",
        "style_affiliation": ["佛山剪纸"],
        "biography": "陈永才，广东佛山人，国家级非物质文化遗产代表性传承人。佛山剪纸的标志性人物。",
        "specialties": ["铜凿剪纸", "金纸剪纸", "佛山传统剪纸"],
        "master_level": "大师级",
        "years_of_experience": 50,
        "representative_works": ["《赛龙舟》", "《佛山古镇图》"],
        "status": "活跃",
        "is_reviewer": True,
    },
    {
        "id": "inheritor_006",
        "name": "范祚信",
        "title": "国家级非遗传承人",
        "gender": "男",
        "birth_year": 1944,
        "region": "山东省高密市",
        "style_affiliation": ["高密剪纸"],
        "biography": "范祚信，山东高密人，国家级非物质文化遗产代表性传承人。以水浒人物剪纸闻名。",
        "specialties": ["人物剪纸", "水浒题材", "锯齿纹技法"],
        "master_level": "大师级",
        "years_of_experience": 50,
        "representative_works": ["《水浒一百单八将》"],
        "status": "活跃",
        "is_reviewer": True,
    },
]

# ========== 材料数据 ==========

SEED_MATERIALS = [
    {
        "id": "material_001",
        "name": "大红宣纸",
        "category": "纸",
        "sub_type": "宣纸",
        "description": "传统手工大红宣纸，质地柔韧、吸色性好，是剪纸最常用的纸张。",
        "specifications": ["四尺", "六尺", "八尺"],
        "recommended_for": ["单色剪纸", "染色剪纸"],
        "is_traditional": True,
    },
    {
        "id": "material_002",
        "name": "电光纸",
        "category": "纸",
        "sub_type": "机制纸",
        "description": "表面带有光泽的机制纸，色彩鲜艳，价格低廉，适合学生和初学者。",
        "specifications": ["A4", "A3", "全开"],
        "recommended_for": ["练习", "儿童剪纸"],
        "is_traditional": False,
    },
    {
        "id": "material_003",
        "name": "金箔纸",
        "category": "纸",
        "sub_type": "特种纸",
        "description": "表面覆有仿金涂层的纸张，在佛山剪纸中广泛使用，具有富丽堂皇的效果。",
        "specifications": ["四尺", "六尺"],
        "recommended_for": ["佛山剪纸", "装饰性剪纸"],
        "is_traditional": True,
    },
    {
        "id": "material_004",
        "name": "刻刀（斜口刀）",
        "category": "刀",
        "sub_type": "刻制工具",
        "description": "斜口刻刀，刀口呈45度斜角，是剪纸刻制最核心的工具。",
        "specifications": ["大号", "中号", "小号", "最小号"],
        "recommended_for": ["阴刻", "阳刻", "阴阳刻"],
        "is_traditional": True,
    },
    {
        "id": "material_005",
        "name": "蜡盘",
        "category": "辅助工具",
        "sub_type": "刻制垫板",
        "description": "用蜡和草木灰制成的软垫板，刻刀切入后能自动闭合，保护刀刃。",
        "specifications": ["圆形", "方形"],
        "recommended_for": ["精细刻制"],
        "is_traditional": True,
    },
    {
        "id": "material_006",
        "name": "剪刀（尖头剪）",
        "category": "刀",
        "sub_type": "剪制工具",
        "description": "尖头剪刀，刃薄锋利，用于剪纸的剪制技法。",
        "specifications": ["全长15cm", "全长20cm"],
        "recommended_for": ["剪制类剪纸", "大幅轮廓"],
        "is_traditional": True,
    },
]

# ========== 母题间关联 ==========

SEED_MOTIF_RELATIONS = [
    {"source_id": "motif_001", "target_id": "motif_002", "relation_type": "组合", "description": "龙凤呈祥经典组合", "strength": 0.9},
    {"source_id": "motif_001", "target_id": "motif_003", "relation_type": "组合", "description": "龙纹常配祥云", "strength": 0.8},
    {"source_id": "motif_002", "target_id": "motif_004", "relation_type": "组合", "description": "凤穿牡丹经典搭配", "strength": 0.85},
    {"source_id": "motif_005", "target_id": "motif_006", "relation_type": "组合", "description": "五福捧寿经典组合", "strength": 0.9},
    {"source_id": "motif_005", "target_id": "motif_012", "relation_type": "组合", "description": "蝙蝠与福字组合", "strength": 0.85},
    {"source_id": "motif_009", "target_id": "motif_011", "relation_type": "组合", "description": "喜鹊登梅经典搭配", "strength": 0.9},
    {"source_id": "motif_010", "target_id": "motif_008", "relation_type": "组合", "description": "鱼戏莲经典组合", "strength": 0.85},
    {"source_id": "motif_008", "target_id": "motif_010", "relation_type": "组合", "description": "鱼戏莲经典组合", "strength": 0.85},
    {"source_id": "motif_001", "target_id": "motif_006", "relation_type": "组合", "description": "龙纹与寿桃的祝寿组合", "strength": 0.5},
    {"source_id": "motif_011", "target_id": "motif_004", "relation_type": "相似", "description": "梅与牡丹同为花卉母题", "strength": 0.4},
    {"source_id": "motif_001", "target_id": "motif_005", "relation_type": "组合", "description": "龙与蝙蝠在祝寿场景中的组合", "strength": 0.5},
]

# ========== 纹样-母题映射 ==========

SEED_PATTERN_MOTIF_MAP = {
    "pc_001": [{"motif_id": "motif_001", "prominence": 0.9, "position": "左侧主图", "is_primary": True},
               {"motif_id": "motif_002", "prominence": 0.9, "position": "右侧主图", "is_primary": True},
               {"motif_id": "motif_003", "prominence": 0.5, "position": "背景装饰"}],
    "pc_002": [{"motif_id": "motif_005", "prominence": 0.8, "position": "上/下两侧", "is_primary": False},
               {"motif_id": "motif_006", "prominence": 0.9, "position": "中央主图", "is_primary": True}],
    "pc_003": [{"motif_id": "motif_009", "prominence": 0.85, "position": "枝头", "is_primary": True},
               {"motif_id": "motif_011", "prominence": 0.8, "position": "枝条", "is_primary": True}],
    "pc_004": [{"motif_id": "motif_010", "prominence": 0.9, "position": "中央主图", "is_primary": True},
               {"motif_id": "motif_008", "prominence": 0.8, "position": "衬底", "is_primary": True}],
    "pc_005": [{"motif_id": "motif_001", "prominence": 1.0, "position": "全幅主图", "is_primary": True},
               {"motif_id": "motif_003", "prominence": 0.6, "position": "背景装饰"}],
    "pc_006": [{"motif_id": "motif_011", "prominence": 0.8, "position": "上左", "is_primary": True},
               {"motif_id": "motif_008", "prominence": 0.8, "position": "上右", "is_primary": True},
               {"motif_id": "motif_004", "prominence": 0.8, "position": "下左", "is_primary": True},
               {"motif_id": "motif_011", "prominence": 0.8, "position": "下右"}],
    "pc_007": [{"motif_id": "motif_005", "prominence": 0.8, "position": "五角分布", "is_primary": False},
               {"motif_id": "motif_012", "prominence": 0.9, "position": "中央", "is_primary": True}],
    "pc_009": [{"motif_id": "motif_004", "prominence": 1.0, "position": "中央主图", "is_primary": True}],
    "pc_011": [{"motif_id": "motif_008", "prominence": 0.9, "position": "并蒂形式", "is_primary": True}],
    "pc_012": [{"motif_id": "motif_010", "prominence": 0.85, "position": "游鱼", "is_primary": True},
               {"motif_id": "motif_008", "prominence": 0.7, "position": "衬底"}],
}

# ========== 纹样-技法映射 ==========

SEED_PATTERN_TECHNIQUE_MAP = {
    "pc_001": [{"technique_id": "tech_003", "is_primary": True, "order": 1}],
    "pc_002": [{"technique_id": "tech_001", "is_primary": True, "order": 1}],
    "pc_003": [{"technique_id": "tech_002", "is_primary": True, "order": 1}],
    "pc_004": [{"technique_id": "tech_003", "is_primary": True, "order": 1}],
    "pc_005": [{"technique_id": "tech_003", "is_primary": True, "order": 1}],
    "pc_006": [{"technique_id": "tech_002", "is_primary": True, "order": 1}],
    "pc_007": [{"technique_id": "tech_003", "is_primary": True, "order": 1}],
    "pc_008": [{"technique_id": "tech_001", "is_primary": True, "order": 1}],
    "pc_009": [{"technique_id": "tech_002", "is_primary": True, "order": 1}],
    "pc_010": [{"technique_id": "tech_003", "is_primary": True, "order": 1}],
    "pc_011": [{"technique_id": "tech_002", "is_primary": True, "order": 1}],
    "pc_012": [{"technique_id": "tech_003", "is_primary": True, "order": 1}],
    "pc_101": [{"technique_id": "tech_003", "is_primary": True, "order": 1}],
    "pc_102": [{"technique_id": "tech_001", "is_primary": True, "order": 1}],
}

# ========== 纹样-流派映射 ==========

SEED_PATTERN_STYLE_MAP = {
    "pc_001": [{"style_id": "style_001", "influence_degree": 0.6, "is_representative": False},
               {"style_id": "style_003", "influence_degree": 0.5, "is_representative": False}],
    "pc_003": [{"style_id": "style_003", "influence_degree": 0.8, "is_representative": True}],
    "pc_005": [{"style_id": "style_003", "influence_degree": 0.7, "is_representative": False}],
    "pc_006": [{"style_id": "style_002", "influence_degree": 0.8, "is_representative": True}],
    "pc_008": [{"style_id": "style_003", "influence_degree": 0.8, "is_representative": True}],
    "pc_009": [{"style_id": "style_002", "influence_degree": 0.7, "is_representative": False}],
    "pc_010": [{"style_id": "style_003", "influence_degree": 0.9, "is_representative": True}],
    "pc_101": [{"style_id": "style_001", "influence_degree": 0.9, "is_representative": True}],
    "pc_102": [{"style_id": "style_001", "influence_degree": 0.9, "is_representative": True}],
}

# ========== 纹样-象征映射 ==========

SEED_PATTERN_SYMBOL_MAP = {
    "pc_001": [{"target_id": "symbol_007", "significance": 0.9, "cultural_note": "婚庆核心主题"},
               {"target_id": "symbol_001", "significance": 0.6}],
    "pc_002": [{"target_id": "symbol_002", "significance": 0.9, "cultural_note": "祝寿核心主题"},
               {"target_id": "symbol_001", "significance": 0.7}],
    "pc_003": [{"target_id": "symbol_003", "significance": 0.9, "cultural_note": "喜鹊报喜"},
               {"target_id": "symbol_005", "significance": 0.5}],
    "pc_004": [{"target_id": "symbol_004", "significance": 0.8, "cultural_note": "年年有余=年年富足"},
               {"target_id": "symbol_001", "significance": 0.5}],
    "pc_005": [{"target_id": "symbol_005", "significance": 0.8},
               {"target_id": "symbol_001", "significance": 0.7}],
    "pc_006": [{"target_id": "symbol_005", "significance": 0.7, "cultural_note": "君子品格"},
               {"target_id": "symbol_008", "significance": 0.5}],
    "pc_007": [{"target_id": "symbol_002", "significance": 0.9, "cultural_note": "祝寿核心主题"},
               {"target_id": "symbol_001", "significance": 0.9}],
    "pc_008": [{"target_id": "symbol_006", "significance": 0.9, "cultural_note": "镇宅辟邪"},
               {"target_id": "symbol_005", "significance": 0.5}],
    "pc_009": [{"target_id": "symbol_008", "significance": 0.9, "cultural_note": "花开富贵"},
               {"target_id": "symbol_001", "significance": 0.5}],
    "pc_010": [{"target_id": "symbol_003", "significance": 0.8, "cultural_note": "得子之喜"},
               {"target_id": "symbol_001", "significance": 0.5}],
    "pc_011": [{"target_id": "symbol_007", "significance": 0.9, "cultural_note": "爱情忠贞"}],
    "pc_012": [{"target_id": "symbol_004", "significance": 0.7},
               {"target_id": "symbol_001", "significance": 0.5}],
}

# ========== 纹样-材料映射 ==========

SEED_PATTERN_MATERIAL_MAP = {
    "pc_001": [{"material_id": "material_001", "is_default": True, "specification_detail": "大红宣纸，四尺"}],
    "pc_002": [{"material_id": "material_001", "is_default": True}],
    "pc_003": [{"material_id": "material_001", "is_default": True}],
    "pc_004": [{"material_id": "material_001", "is_default": True}],
    "pc_005": [{"material_id": "material_001", "is_default": True}],
    "pc_006": [{"material_id": "material_001", "is_default": True}],
    "pc_007": [{"material_id": "material_001", "is_default": True}],
    "pc_009": [{"material_id": "material_001", "is_default": True}],
    "pc_101": [{"material_id": "material_001", "is_default": True}],
    "pc_102": [{"material_id": "material_003", "is_default": True, "specification_detail": "金箔纸，长卷"}],
}

# ========== 汇总函数 ==========

def get_all_seed_data():
    """获取全部种子数据的聚合字典"""
    return {
        "patterns": SEED_PAPER_CUT_PATTERNS,
        "motifs": SEED_MOTIFS,
        "techniques": SEED_TECHNIQUES,
        "regional_styles": SEED_REGIONAL_STYLES,
        "cultural_symbols": SEED_CULTURAL_SYMBOLS,
        "inheritors": SEED_INHERITORS,
        "materials": SEED_MATERIALS,
        "motif_relations": SEED_MOTIF_RELATIONS,
        "pattern_motif_map": SEED_PATTERN_MOTIF_MAP,
        "pattern_technique_map": SEED_PATTERN_TECHNIQUE_MAP,
        "pattern_style_map": SEED_PATTERN_STYLE_MAP,
        "pattern_symbol_map": SEED_PATTERN_SYMBOL_MAP,
        "pattern_material_map": SEED_PATTERN_MATERIAL_MAP,
    }


def get_seed_summary():
    """返回种子数据统计"""
    return {
        "patterns": len(SEED_PAPER_CUT_PATTERNS),
        "motifs": len(SEED_MOTIFS),
        "techniques": len(SEED_TECHNIQUES),
        "regional_styles": len(SEED_REGIONAL_STYLES),
        "cultural_symbols": len(SEED_CULTURAL_SYMBOLS),
        "inheritors": len(SEED_INHERITORS),
        "materials": len(SEED_MATERIALS),
        "motif_relations": len(SEED_MOTIF_RELATIONS),
        "pattern_motif_links": sum(len(v) for v in SEED_PATTERN_MOTIF_MAP.values()),
        "pattern_technique_links": sum(len(v) for v in SEED_PATTERN_TECHNIQUE_MAP.values()),
        "pattern_style_links": sum(len(v) for v in SEED_PATTERN_STYLE_MAP.values()),
        "pattern_symbol_links": sum(len(v) for v in SEED_PATTERN_SYMBOL_MAP.values()),
        "pattern_material_links": sum(len(v) for v in SEED_PATTERN_MATERIAL_MAP.values()),
    }


if __name__ == "__main__":
    summary = get_seed_summary()
    print("种子数据统计:")
    print(f"  纹样: {summary['patterns']} 个")
    print(f"  母题: {summary['motifs']} 个")
    print(f"  技法: {summary['techniques']} 种")
    print(f"  地域流派: {summary['regional_styles']} 个")
    print(f"  文化象征: {summary['cultural_symbols']} 个")
    print(f"  传承人: {summary['inheritors']} 位")
    print(f"  材料工具: {summary['materials']} 种")
    print(f"  母题间关联: {summary['motif_relations']} 条")
    print(f"  纹样-母题映射: {summary['pattern_motif_links']} 条")
    print(f"  纹样-技法映射: {summary['pattern_technique_links']} 条")
    print(f"  纹样-流派映射: {summary['pattern_style_links']} 条")
    print(f"  纹样-象征映射: {summary['pattern_symbol_links']} 条")
    print(f"  纹样-材料映射: {summary['pattern_material_links']} 条")
